#!/usr/bin/env bash
set -u

if [ -n "${BASH_SOURCE:-}" ] && [ -n "${BASH_SOURCE[0]:-}" ]; then
  SCRIPT_PATH="${BASH_SOURCE[0]}"
else
  SCRIPT_PATH="$0"
fi

SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
cd "$SCRIPT_DIR"

export TRADING_BOT_SYMBOL="${TRADING_BOT_SYMBOL:-FNGU}"
export TRADING_BOT_BUY_THRESHOLD="${TRADING_BOT_BUY_THRESHOLD:--0.0125}"
export TRADING_BOT_SELL_THRESHOLD="${TRADING_BOT_SELL_THRESHOLD:=0.025}"
export TRADING_BOT_SIGNAL_ONLY="false"
export TRADING_BOT_ALLOW_AFTER_HOURS="${TRADING_BOT_ALLOW_AFTER_HOURS:-true}"
export TRADING_BOT_RESPECT_MARKET_HOURS="${TRADING_BOT_RESPECT_MARKET_HOURS:-false}"
export TRADING_BOT_LIVE_TRADING="true"
export TRADING_BOT_INTERVAL="${TRADING_BOT_INTERVAL:-5m}"

printf 'Live config: %s buy=%s sell=%s signal_only=%s live=%s allow_after_hours=%s\n' \
  "$TRADING_BOT_SYMBOL" "$TRADING_BOT_BUY_THRESHOLD" "$TRADING_BOT_SELL_THRESHOLD" \
  "$TRADING_BOT_SIGNAL_ONLY" "$TRADING_BOT_LIVE_TRADING" "$TRADING_BOT_ALLOW_AFTER_HOURS"

python3 trading_bot.py
