#!/usr/bin/env bash
set -u

if [ -n "${BASH_SOURCE:-}" ] && [ -n "${BASH_SOURCE[0]:-}" ]; then
  SCRIPT_PATH="${BASH_SOURCE[0]}"
else
  SCRIPT_PATH="$0"
fi

SCRIPT_DIR="$(cd "$(dirname "$SCRIPT_PATH")" && pwd)"
cd "$SCRIPT_DIR"

export BACKTEST_SYMBOL="${BACKTEST_SYMBOL:-FNGU}"
export BACKTEST_INTERVAL="${BACKTEST_INTERVAL:-5m}"
export BACKTEST_CASH="${BACKTEST_CASH:-5000}"
export BACKTEST_START="${BACKTEST_START:-2026-08-16}"
export BACKTEST_END="${BACKTEST_END:-2026-09-18}"
export BACKTEST_BUY_THRESHOLD="${BACKTEST_BUY_THRESHOLD:--0.001}"
export BACKTEST_SELL_THRESHOLD="${BACKTEST_SELL_THRESHOLD:=0.001}"
export BACKTEST_STRATEGY_FILE="${BACKTEST_STRATEGY_FILE:-strategy_presets.json}"
export BACKTEST_STRATEGY_NAME="${BACKTEST_STRATEGY_NAME:-pyramid_buy_sell}"
export BACKTEST_MULTI_SYMBOLS="${BACKTEST_MULTI_SYMBOLS:-SOXL,TQQQ,FNGU}"

printf 'Backtest defaults: symbol=%s interval=%s cash=%s start=%s end=%s buy=%s sell=%s strategy=%s\n' \
  "$BACKTEST_SYMBOL" "$BACKTEST_INTERVAL" "$BACKTEST_CASH" "$BACKTEST_START" "$BACKTEST_END" \
  "$BACKTEST_BUY_THRESHOLD" "$BACKTEST_SELL_THRESHOLD" "$BACKTEST_STRATEGY_NAME"
